name: Sync from upstream repository

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC.
  workflow_dispatch:  # Allows you to manually trigger the action.

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout forked repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Add upstream
      run: git remote add upstream https://github.com/garenj/Acclimation-scaling.git

    - name: Fetch upstream
      run: git fetch upstream

    - name: Set up Git user
      run: |
        git config --local user.email "sean.michaletz@gmail.com"
        git config --local user.name "Sean Michaletz"

    - name: Merge upstream changes with unrelated histories and conflict resolution
      run: |
        git merge upstream/main --allow-unrelated-histories --strategy-option theirs || true

    - name: Push changes if merge was successful
      if: success()
      run: git push origin main  # Replace 'main' with your fork's default branch if needed
