name: Sync from upstream repository

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC. You can adjust the cron timing.
  workflow_dispatch:  # Allows you to manually trigger the action from the Actions tab.

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout forked repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Add upstream
      run: git remote add upstream https://github.com/garenj/Acclimation-scaling.git  # Original repository URL

    - name: Fetch upstream
      run: git fetch upstream

    - name: Merge upstream changes
      run: git merge upstream/main  # Replace 'main' if the default branch is different

    - name: Push changes
      run: git push origin main  # Replace 'main' with your fork's default branch if needed
